#!/usr/bin/awk -f

BEGIN {
  actual = 1000
  expected = 1000
  burn = 30
  expected_timestamp = 100000
  timestamp = 0
}

{
  if(timestamp == 0) {
    expected_timestamp = $1
  }
  timestamp = $1
  actual -= $2
  if (expected_timestamp < timestamp) {
    expected_timestamp += 86400
    expected -= burn
  }
  printf "%s\t%d\t%d\n", $1, actual, expected
}

END {
  while (expected > burn) {
    timestamp += 86400
    expected -= burn
    printf "%s\t%d\t%d\n", timestamp, -1, expected
  }
}
