#!/bin/sh

if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    echo "Usage daily <n>"
    echo "n - number of cranes"
  else
    echo "\n$(date +%s)\t$1\c" -n >> senbazuru.txt
    ./burndown senbazuru.txt > burndown.txt
fi
